# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mhdlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MHDlg(object):
    def setupUi(self, MHDlg):
        MHDlg.setObjectName("MHDlg")
        MHDlg.resize(738, 575)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(MHDlg)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(MHDlg)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.mid_editor = QtWidgets.QLineEdit(MHDlg)
        self.mid_editor.setObjectName("mid_editor")
        self.horizontalLayout.addWidget(self.mid_editor)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.chs_table = QtWidgets.QTableView(MHDlg)
        self.chs_table.setSortingEnabled(True)
        self.chs_table.setObjectName("chs_table")
        self.verticalLayout.addWidget(self.chs_table)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.get_chs_btn = QtWidgets.QPushButton(MHDlg)
        self.get_chs_btn.setObjectName("get_chs_btn")
        self.verticalLayout_2.addWidget(self.get_chs_btn)
        self.download_btn = QtWidgets.QPushButton(MHDlg)
        self.download_btn.setObjectName("download_btn")
        self.verticalLayout_2.addWidget(self.download_btn)
        self.exit_btn = QtWidgets.QPushButton(MHDlg)
        self.exit_btn.setObjectName("exit_btn")
        self.verticalLayout_2.addWidget(self.exit_btn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)

        self.retranslateUi(MHDlg)
        self.exit_btn.clicked.connect(MHDlg.close)
        self.get_chs_btn.clicked.connect(MHDlg.get_chapters)
        self.download_btn.clicked.connect(MHDlg.download_jpgs)
        QtCore.QMetaObject.connectSlotsByName(MHDlg)
        MHDlg.setTabOrder(self.mid_editor, self.chs_table)
        MHDlg.setTabOrder(self.chs_table, self.get_chs_btn)
        MHDlg.setTabOrder(self.get_chs_btn, self.download_btn)
        MHDlg.setTabOrder(self.download_btn, self.exit_btn)

    def retranslateUi(self, MHDlg):
        _translate = QtCore.QCoreApplication.translate
        MHDlg.setWindowTitle(_translate("MHDlg", "漫画下载工具"))
        self.label.setText(_translate("MHDlg", "输入漫画id:"))
        self.get_chs_btn.setText(_translate("MHDlg", "获取章节列表"))
        self.download_btn.setText(_translate("MHDlg", "下载选中章节"))
        self.exit_btn.setText(_translate("MHDlg", "退出"))
