# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mhdlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MHDlg(object):
    def setupUi(self, MHDlg):
        MHDlg.setObjectName("MHDlg")
        MHDlg.resize(738, 575)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(MHDlg)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(MHDlg)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.mid_editor = QtWidgets.QLineEdit(MHDlg)
        self.mid_editor.setObjectName("mid_editor")
        self.horizontalLayout.addWidget(self.mid_editor)
        self.label_2 = QtWidgets.QLabel(MHDlg)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.thread_spin = QtWidgets.QSpinBox(MHDlg)
        self.thread_spin.setMinimum(1)
        self.thread_spin.setSingleStep(3)
        self.thread_spin.setProperty("value", 10)
        self.thread_spin.setObjectName("thread_spin")
        self.horizontalLayout.addWidget(self.thread_spin)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.mahua_title = QtWidgets.QLabel(MHDlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mahua_title.setFont(font)
        self.mahua_title.setText("")
        self.mahua_title.setAlignment(QtCore.Qt.AlignCenter)
        self.mahua_title.setObjectName("mahua_title")
        self.verticalLayout.addWidget(self.mahua_title)
        self.chs_table = QtWidgets.QTableView(MHDlg)
        self.chs_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.chs_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.chs_table.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.chs_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.chs_table.setSortingEnabled(True)
        self.chs_table.setObjectName("chs_table")
        self.chs_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.chs_table)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.get_chs_btn = QtWidgets.QPushButton(MHDlg)
        self.get_chs_btn.setObjectName("get_chs_btn")
        self.verticalLayout_2.addWidget(self.get_chs_btn)
        self.download_btn = QtWidgets.QPushButton(MHDlg)
        self.download_btn.setObjectName("download_btn")
        self.verticalLayout_2.addWidget(self.download_btn)
        self.exit_btn = QtWidgets.QPushButton(MHDlg)
        self.exit_btn.setObjectName("exit_btn")
        self.verticalLayout_2.addWidget(self.exit_btn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)

        self.retranslateUi(MHDlg)
        self.exit_btn.clicked.connect(MHDlg.close)
        self.get_chs_btn.clicked.connect(MHDlg.get_chapters)
        self.download_btn.clicked.connect(MHDlg.download_jpgs)
        self.thread_spin.valueChanged['int'].connect(MHDlg.change_max_thread)
        QtCore.QMetaObject.connectSlotsByName(MHDlg)
        MHDlg.setTabOrder(self.chs_table, self.get_chs_btn)
        MHDlg.setTabOrder(self.get_chs_btn, self.download_btn)
        MHDlg.setTabOrder(self.download_btn, self.exit_btn)

    def retranslateUi(self, MHDlg):
        _translate = QtCore.QCoreApplication.translate
        MHDlg.setWindowTitle(_translate("MHDlg", "漫画下载工具"))
        self.label.setText(_translate("MHDlg", "输入漫画id:"))
        self.label_2.setText(_translate("MHDlg", "并发数量："))
        self.get_chs_btn.setText(_translate("MHDlg", "获取章节列表"))
        self.download_btn.setText(_translate("MHDlg", "下载选中章节"))
        self.exit_btn.setText(_translate("MHDlg", "退出"))
